language:
  - cpp

  addons:
  apt:
    sources:
    - llvm-toolchain-precise
    packages:
    - clang++-3.7

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./GraphicsLib/GraphicsLibTest
  - ./Interpreter/InterpreterTest

notifications:
  email: cui@hellolw.com
