language:
  - cpp

  addons:
      apt:
          sources:
              - llvm-toolchain-precise
              - ubuntu-toolchain-r-test
          packages:
              - clang++-3.7
              - g++-5

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./GraphicsLib/GraphicsLibTest
  - ./Interpreter/InterpreterTest

notifications:
  email: cui@hellolw.com
