language:
  - cpp

<<<<<<< HEAD
compiler:
  - clang

before_install:
  # clang 3.6
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

install:
  # clang 3.6
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.6; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.6"; fi

script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./GraphicsLib/GraphicsLibTest
  - ./Interpreter/InterpreterTest

notifications:
  email: cui@hellolw.com
